var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};var em;
function getValue(a){a=document.getElementById(a);a.style.height="1em";em=a.offsetHeight}getValue("em-div");
window.location.query||(window.location.query=function(a){var b=new Map;a=a||this.search;if(""!=a){var d=a;0==d.indexOf("?")&&(d=d.substr(1));d=d.split("&");for(c in d){a=d[c].split("=",("="!==d[c].slice(-1))+1);var c=decodeURIComponent(a[0]);a=a[1];a="undefined"===typeof a?a:decodeURIComponent(a);b.has(c)?("[object Array]"!==Object.prototype.toString.call(b.get(c))&&b.set(c,[b.get(c)]),b.set(c,b.get(c).push(a))):b.set(c,a)}}return b});
var qrymap=window.location.query(),mapfile="small-ctrys-50m-c-10km2-1e6.json",svg=d3.select("svg"),header=d3.select("#header"),header2=d3.select("#header2"),div=d3.select("#viewport"),canvas=d3.select("canvas").node().getContext("2d"),ctytog=0,loctog=!1,loctog2=-1,r_key,median;d3.select("#ct").on("click",togglectry);d3.select("#cl").on("click",toggleclique);d3.select("#sv").on("click",togglepickle);d3.select("#ATEAM").on("click",ateam);function ateam(){change_filter();redraw()}
function togglectry(){0!=ctytog&&remove_checkboxes("#adv");1!=ctytog?(make_checkboxes("#adv",countries,ctrymask,mb_mask_or,mask_callback(ctrymask,"#adv")),ctytog=1):ctytog=0}function toggleclique(){0!=ctytog&&remove_checkboxes("#adv");2!=ctytog?(0!=menu_vars.group?d3.select("#adv").append("span").attr("class","inputs").text("No cliques outside Group 0!"):make_checkboxes("#adv",cliques,cliquemask,mb_mask_or,mask_callback(cliquemask,"#adv")),ctytog=2):ctytog=0}
function togglepickle(){0!=ctytog&&remove_checkboxes("#adv");3!=ctytog?(make_pickle(),ctytog=3):ctytog=0}function make_pickle(){var a=d3.select("#adv");a.append("span").attr("class","inputs").text("Not implemented yet!");a.append("input").attr("type","text").attr("class","inputs").attr("id","textbox");a.append("span").attr("class","inputs").text("SAVE").on("click",save_settings);a.append("span").attr("class","inputs").text("LOAD").on("click",load_settings)}
function togglelocator(){loctog?removelocator():makelocator();loctog=!loctog}
function makelocator(){d3.select("#locator").style("visibility","visible");var a=d3.select("#locator svg").attr("height",Math.round(2.2*cities.size()*em)).selectAll("g").data(cities.keys().sort(),function(a){return a});a.exit().remove();a=a.enter().append("g").attr("transform",function(a,d){return"translate(0,"+Math.round(2.2*d*em)+")"});a.append("rect").attr("fill","aliceblue").attr("opacity",.9).attr("stroke","steelblue").attr("width","10em").attr("height","2em").on("click",togglelocator2);a.append("text").attr("fill-opacity",
1).attr("x","5").attr("y","1.2em").text(function(a){return a})}
function togglelocator2(a,b,d){if(-1<loctog2)removelocator2(d[loctog2]);else{makelocator2(a,d[b]);d=countries_list.get(a);var c=path.bounds(d),c=.8/Math.max((c[1][0]-c[0][0])/width,(c[1][1]-c[0][1])/width);coords=d.properties.centre;projection.rotate([-coords[0],-coords[1]]);svg.call(zoom.scaleBy,c);canvas.beginPath();canvaspath(d);canvas.fillStyle="ivory";canvas.fill();citiepts=[];cities.get(a).forEach(function(a){citiepts.push([a[0],a[1]])});canvas.beginPath();canvaspath({type:"MultiPoint",coordinates:citiepts});
canvas.strokeStyle="steelblue";canvas.stroke()}loctog2=-1<loctog2?-1:b}
function makelocator2(a,b){d3.select("#locator2").style("visibility","visible");b.setAttribute("fill","ivory");citieslist=cities.get(a).slice().sort(function(a,b){return a[3]>b[3]?1:a[3]<b[3]?-1:0});var d=d3.select("#locator2 svg").attr("height",Math.round(2.2*citieslist.length*em)).selectAll("g").data(citieslist,function(a){return a[3]});d.exit().remove();d=d.enter().append("g").merge(d).attr("transform",function(a,b){return"translate(0,"+Math.round(2.2*b*em)+")"});d.append("rect").attr("fill","aliceblue").attr("opacity",
.9).attr("stroke","steelblue").attr("width","10em").attr("height","2em").on("click",zoom2);d.append("text").attr("fill-opacity",1).attr("x","5").attr("y","1.2em").text(function(a){return a[3]})}
function zoom2(a,b,d){b=countries_list.get(a[2]);projection.rotate([-a[0],-a[1]]);svg.call(zoom.scaleTo,32);canvas.beginPath();canvaspath(b);canvas.fillStyle="ivory";canvas.fill();citiepts=[];cities.get(a[2]).forEach(function(a){citiepts.push([a[0],a[1]])});coords=projection([a[0],a[1]]);canvas.beginPath();canvaspath({type:"MultiPoint",coordinates:citiepts});canvas.strokeStyle="steelblue";canvas.stroke();canvas.beginPath();canvaspath({type:"Point",coordinates:[a[0],a[1]]});canvas.fillStyle="red";
canvas.fill();canvas.fillText(a[3],coords[0]+10,coords[1])}function removelocator2(a){a.setAttribute("fill","aliceblue");d3.select("#locator2").style("visibility","hidden")}function removelocator(){d3.select("#locator").style("visibility","hidden");d3.select("#locator2").style("visibility","hidden")}function modetoggle(){modeimg=map?"map-icon.png":"list-icon.png";d3.select("#modetoggle").attr("src",modeimg);d3.select("#modetoggle").on("click",null);1==map?map_to_list():list_to_map()}
function default_loader(){function a(a){return function(){markerradius=a;redraw()}}countries=[];genders=[["Women",[1]],["Men",[2]],["Coed",[4]],["Junior",[8]]];world=0;teamparse=[];ratingsparse=[];sortedr=[];sorted_map=new Map;ratingslists=new Map;teamparse=[];ratingsparse=[];sortedr=[];sorted_map=new Map;map=!1;ctrymask=[4294967295,4294967295];gendermask=[15];menu_vars={group:-1,col:0};defaultsrc="SRDRank2.2";defaultdate=!1;markerradius=.15;tooltips={rs:["Rating Source","Select the Rating kind you want here.<br />The default is the SRDRank, which ranks all the teams who can be ranked (regardless of gender or location).<br />We also offer WFTDA Rankings, with others coming soon.<br />Selecting a type of Rating changes the Dates available to get Ratings for."],
dt:["Date","Select the Date you want the Ratings from.<br />The available Dates are determined by the Rating Source you chose."],rg:["Rating Group","SRD Rank will only compare Groups of Teams who are connected via a chain of games in the last year.<br />Selecting a Rating Group picks one of those Groups to view the Ratings for, for the current Date.<br />(In Map Mode, you can also view ALL Groups to see every team that played at all on the map at once.)"],gt:['"Gender" Types','Select the "Gender" of teams you would like to view. The INVERT button reverses the selections.'],
cg:["Colour Grouping",'Select a system for colouring the teams. Different options will be available based on other choices. In Map mode, all teams of a given colour are grouped under that colour in the icon.<br /><br />"Groups" colours by Rating Group.<br />"Genders" colours by Gender.<br />For Group 0 only, Cliques colours by cliques within Group 0 (see Cliques menu for more info)'],ct:["Countries","[Click this button to get the countries tab]<br />Select the countries you would like to see teams for. The INVERT button reverses the selections."],
cl:["Cliques","[Click this button to get the cliques tab]<br />Select cliques to show.<br />A 'clique' is a set of teams who have played each other a lot, but the outside world much less.<br />As a result, their 'local' ratings are more accurate than their global placement.<br />SRDRank detects cliques as part of the rating process, but only for Group 0, the largest group."],sv:["Load/Save","[Click this button to get the load/save tab]<br />Save the current selection and config (as a sequence you can copy and paste), or load a previously saved config.</br >Just copy the textbox contents!"]};
d3.selectAll(".tooltip").each(function(){p=d3.select(this);values=tooltips[this.id];p.text(values[0]);txt=p.insert("span").attr("class","tooltiptxt");txt.html(values[1])});mkrcblt={small:.05,medium:.15,large:.45};d3.selectAll(".markersize").each(function(){p=this.id;this.addEventListener("click",a(mkrcblt[p]))});modetxt=map?"list-icon.png":"map-icon.png";d3.select("#modetoggle").attr("src",modetxt).on("click",modetoggle);d3.select("#locatortoggle").on("click",togglelocator);0<qrymap.size&&console.log(qrymap)}
function load_settings(){load_settings_(d3.select("#textbox").attr("value"))}
function load_settings_(a){tmpvector=a.split(",");defaultsrc=tmpvector[0];defaultdate=datedecode(tmpvector[1]);a=valdecode(tmpvector[2]);ctrymask=vectdecode(tmpvector[3]);cliquemask=vectdecode(tmpvector[4]);gendermask=vectdecode(tmpvector[5]);menu_vars.group=valdecode(tmpvector[6]);menu_vars.col=valdecode(tmpvector[7]);rotatetmp=coorddecode(tmpvector[8]);var b=rotatetmp.slice(0,3),d=rotatetmp[3];d3.select("#type select").property("value",defaultsrc);type_menu_callback(defaultsrc+"/"+defaultdate+".out");
a!=map&&(a?list_to_map():map_to_list());projection.rotate(b);projection.scale(scale0*d);redraw()}
function save_settings(){tmpvector=[];tmpvector[0]=d3.select("#type select").property("value");var a=d3.select("#dates select").property("value");tmpvector[1]=dateencode(a.slice(tmpvector[0].length+1,a.length-3));tmpvector[2]=valencode(map,1);tmpvector[3]=vectencode(ctrymask);tmpvector[4]=vectencode(cliquemask);tmpvector[5]=vectencode(gendermask);tmpvector[6]=valencode(menu_vars.group,1);tmpvector[7]=valencode(menu_vars.col,1);projection?(rotatetmp=projection.rotate(),rotatetmp.push(projection.scale/
scale0)):rotatetmp=[0,0,0,1];tmpvector[8]=coordencode(rotatetmp);d3.select("#textbox").attr("value",tmpvector.join())}var markerradius,cliques,defaultsrc="SRDRank2.2",defaultdate=!1,map=!0,psv=d3.dsvFormat("|"),ratingslists=new Map,teamparse=[],ratingsparse=[],sortedr=[],sorted_map=new Map,countries=[],cities,ctrymask=[4294967295,4294967295],cliquemask=[4294967295,4294967295],world=0,genders,gendermask=[15],menu_vars={group:-3,col:0};default_loader();
var mb_mask_or=function(a,b){for(var d=0;d<a.length;d++)if(0!=(a[d]&b[d]))return!0;return!1},mb_mask_and=function(a,b){for(var d=0;d<a.length;d++)if((a[d]&b[d])!=a[d])return!1;return!0};function calc_mask(a,b){for(var d=0;d<a.length;d++)a[d]=0;d3.select(b).selectAll("input").each(function(c){cb=d3.select(this);if(cb.property("checked"))for(var b=1;b<c.length;b++)a[b-1]|=c[b]})}function mask_callback(a,b){return function(){calc_mask(a,b);change_filter();redraw()}}
function make_checkboxes(a,b,d,c,e){b=d3.select(a).selectAll(".inputs").data(b);b.exit().remove();b.enter().insert("span").attr("class",function(a){return"inputs x"+(+a[1]).toString(16)}).text(function(a){return a[0]}).append("input").attr("type","checkbox").attr("value",function(a){return a.slice(1)}).attr("checked",function(a){return c(a.slice(1),d)?"checked":null}).on("change",e);b.selectAll("input").attr("checked",function(a){return c(a.slice(1),d)});b=d3.select(a).selectAll("input");d3.select(a).selectAll(".invert").data([!0],
function(a){return a}).enter().append("span").text("INVERT").attr("class","invert").on("click",function(b,c){return function(){b.each(function(b){this.checked=!this.checked;calc_mask(d,a)});c()}}(b,e))}function remove_checkboxes(a){d3.select(a).selectAll(".inputs").remove();d3.select(a).select(".invert").remove()}
function update_menu(a,b,d,c){a=d3.select(a+" select").on("change",d);menu_opts=a.selectAll("option").data(b,function(a){return a[1]});menu_opts.exit().remove();menu_opts.enter().insert("option").attr("value",function(a){return a[1]}).text(function(a){return a[0]});a.property("value",c)}function menu_callback(a,b){return function(){menu_vars[b]=d3.select(a+" select").property("value");"group"==b&&(listcomp=null);change_filter();redraw()}}
function load_ranking(a){d3.queue().defer(d3.text,a).await(processranking)}
function processranking(a,b){ratingsparse=psv.parseRows(b);grp0=ratingsparse.filter(function(a){return 0==a[1]});var d=grp0.reduce(function(a,b){return+a<+b[2]?b[2]:a},0);cliques=[];for(var c=0;c<=d;c++)cliques[c]=32>c?[c,1<<c,0]:[c,0,1<<c-32];d=0;null!==listcomp&&(d=1);for(c=0;c<ratingsparse.length;c++)ratingsparse[c][2]=32>ratingsparse[c][2]?[1<<ratingsparse[c][2],0]:[0,1<<ratingsparse[c][2]-32],ratingsparse[c].push(c+1),ratingsparse[c].push.apply(ratingsparse[c],[].concat($jscomp.arrayFromIterable(teamparse.get(ratingsparse[c][0]).slice(1)))),
null!==listcomp&&ratingsparse[c][0]==listcomp[0]&&(listcomp=ratingsparse[c],d=0);median=300/ratingsparse[Math.round(ratingsparse.length/2)][3];1==d&&(listcomp=null);d=[];numgrps=ratingsparse[ratingsparse.length-1][1];for(c=0;c<=numgrps;c++)d.push([c,+c]);d.unshift(["ALL",-1]);menu_vars.group>=numgrps&&(menu_vars.group=-3);-3==menu_vars.group&&(menu_vars.group=0,1==map&&(menu_vars.group=-1));update_menu("#group",d,menu_callback("#group","group"),menu_vars.group);1!=map&&d3.select("#group select option").attr("disabled",
!0);change_filter();redraw()}d3.queue().defer(d3.text,"SRDRankList.psv").defer(d3.text,"teams-vector.uniform").defer(d3.text,"country-vector.uniform").defer(d3.text,"cities-vector.uniform").await(ready_initial);
function make_type_menu(a,b){b=void 0===b?!1:b;var d=d3.select("#type select").on("change",type_menu_callback);menu_opts=d.selectAll("option").data([].concat($jscomp.arrayFromIterable(ratingslists.keys())),function(a){return a});menu_opts.exit().remove();menu_opts.enter().insert("option").attr("value",function(a){return a}).merge(d).text(function(a){return a});d.property("value",a);type_menu_callback(b)}
function date_menu_callback(){var a=d3.select("#dates select").property("value");load_ranking(a)}
function type_menu_callback(a){a=void 0===a?!1:a;r_key=d3.select("#type select").property("value");var b=ratingslists.get(r_key),d=d3.select("#dates select").on("change",date_menu_callback);menu_opts=d.selectAll("option").data(b,function(a){return a[1]});menu_opts.exit().remove();menu_opts.enter().insert("option").attr("value",function(a){return r_key+"/"+a[1]+".out"}).merge(d).text(function(a){return a[1]});0!=a?d.property("value",a):d.property("value",r_key+"/"+b[b.length-1][1]+".out");date_menu_callback()}
function ready_initial(a,b,d,c,e){if(a)return console.log("error: "+a.responseText);teamparse=d3.map(psv.parseRows(d),function(a){return a[0]});countries=psv.parseRows(c);cities=d3.nest().key(function(a){return a[2]}).map(psv.parseRows(e));ratingslists=d3.nest().key(function(a){return a[0]}).map(psv.parseRows(b));make_type_menu(defaultsrc);make_checkboxes("#gender",genders,gendermask,mb_mask_or,mask_callback(gendermask,"#gender"));1==map?d3.queue().defer(d3.json,mapfile).await(processmap):init_list()}
var width=40*em,height=40*em,scale0=300,radii=[.08,.15,.3],g,group,projection,path,canvaspath,zoom=d3.zoom().scaleExtent([1,32]).on("zoom",zoomed).on("start",zoomstart),v0,r0,q0;function zoomstart(){v0=versor.cartesian(projection.invert(d3.mouse(this)));r0=projection.rotate();q0=versor(r0)}
function zoomed(){zoom_trans=d3.event.transform;var a=versor.cartesian(projection.rotate(r0).invert(d3.mouse(this))),a=versor.multiply(q0,versor.delta(v0,a)),a=versor.rotation(a);projection.rotate(a).scale(scale0*zoom_trans.k);render();svg.selectAll("path").attr("d",path)}colorschemas=[["Gender",0],["Cliques",1],["Groups",2]];update_menu("#menu",colorschemas,menu_callback("#menu","col"),0);
scolmap=d3.map().set(1,"#1f77b4").set(2,"#aec7e8").set(4,"#ff7f0e").set(8,"#ffbb78").set(16,"#2ca02c").set(32,"#98df8a").set(64,"#d62728").set(128,"#ff9896").set(256,"#9467bd").set(512,"#c5b0d5").set(1024,"#8c564b").set(2048,"#c49c94").set(4096,"#e377c2").set(8192,"#f7b6d2").set(16384,"#7f7f7f").set(32768,"#c7c7c7").set(65536,"#bcbd22").set(131072,"#dbdb8d").set(262144,"#17becf").set(524288,"#9edae5");gcolmapf=function(a){return a[12]};scolmapf=function(a){return+a[2][0]};
grcolmapf=function(a){return 1<<+a[1]};colmap=[gcolmapf,scolmapf,grcolmapf];var redraw=redraw_list;function map_to_list(){destroy_map();map=!1;init_list();redraw=redraw_list;0<sortedr.length&&redraw();d3.select("#modetoggle").on("click",modetoggle)}
function change_filter(){var a=gendermask[0],b=menu_vars.col,d=d3.select("#ATEAM").property("checked")?!0:!1;console.log(d3.select("#ATEAM").property("checked"));var c=menu_vars.group;sortedr=ratingsparse.filter(function(a){return-1==c?!0:a[1]==c}).filter(function(a){return 0!=c?!0:mb_mask_or(a[2],cliquemask)}).filter(function(a){return mb_mask_or(a.slice(15,17),ctrymask)}).filter(function(a){return d?"Travel Team"==a[11]:!0}).filter(function(b){return 0!=(b[12]&a)}).sort(function(a,b){return a[7]-
b[7]});if(-1==c)for(var e=1;e<=sortedr.length;e++)sortedr[e-1][8]="";else for(e=1;e<=sortedr.length;e++)sortedr[e-1][8]=e;map&&(sorted_map=d3.nest().key(function(a){return a[14]}).key(function(a){return a[13]}).key(colmap[b]).map(sortedr),sorted_coords=[],sorted_map.keys().forEach(function(a){sorted_map.get(a).keys().forEach(function(b){sorted_coords.push([a,b])})}))}
function list_to_map(){destroy_list();map=!0;change_filter();0==world?d3.queue().defer(d3.json,mapfile).await(processmap):(init_map(),redraw=redraw_map,0!=sorted_map.size&&redraw(),d3.select("#modetoggle").on("click",modetoggle))}
function processmap(a,b){world=b;bb=div.node().getBoundingClientRect();dims=bb.bottom-bb.top;projection=d3.geoOrthographic().translate([dims/2,dims/2]).scale(scale0);path=d3.geoPath().projection(projection);canvaspath=d3.geoPath().projection(projection).context(canvas);graticule=d3.geoGraticule10();countries_path=topojson.mesh(world,world.objects["small-ctry-50m-withcentre"]);countries_list=d3.map(topojson.feature(world,world.objects["small-ctry-50m-withcentre"]).features,function(a){return a.properties.name});
init_map();redraw=redraw_map;0!=sorted_map.size&&redraw();d3.select("#modetoggle").on("click",modetoggle)}function render(){canvas.clearRect(0,0,width,width);canvas.beginPath();canvaspath({type:"Sphere"});canvas.fillStyle="#fff";canvas.fill();canvas.beginPath();canvaspath(graticule);canvas.strokeStyle="#ddd";canvas.stroke();canvas.beginPath();canvaspath(countries_path);canvas.strokeStyle="#666";canvas.stroke()}var countries_path,graticule,countries_list;
function init_map(){bb=div.node().getBoundingClientRect();width=bb.right-bb.left;canvas.canvas.width=width;canvas.canvas.height=width;d3.select("#group select option").attr("disabled",null);div.style("overflow-y","visible");dims=svg.attr("width");svg.attr("height",dims);group=svg.insert("g").attr("class","maplayer");d3.selectAll("#markertoggle").style("visibility","visible");d3.selectAll("#locatortoggle").style("visibility","visible");render();g=group.insert("g").attr("class","teams");group.insert("rect").attr("height",
2*em).attr("width",10*em).attr("fill","aliceblue").attr("stroke-width","1px").attr("stroke","steelblue").attr("id","tooltip-map").style("display","none");group.insert("g").attr("id","tooltip-map-text").style("display","none");svg.call(zoom)}function destroy_map(){width=canvas.canvas.width;svg.on(".zoom",null);group.remove();sorted_map.clear();canvas.clearRect(0,0,width,width)}
function redraw_map(){var a=d3.local(),b=d3.local(),d=d3.local();circs=g.selectAll("g").data(sorted_coords,function(a){return a});circs.exit().remove();circs_=circs.enter().insert("g").merge(circs).each(function(c){a.set(this,c);b.set(this,sorted_map.get(c[0]).get(c[1]));d.set(this,sorted_map.get(c[0]).get(c[1]).size())});cgcs=circs_.selectAll("path").data(function(b){var c=a.get(this);var d=markerradius;b=[].concat($jscomp.arrayFromIterable(sorted_map.get(b[0]).get(b[1]).keys()));polygons=[];var e=
b.length;if(1==e){var h=[];h[0]=d3.geoRotation([c[0],0])(d3.geoRotation([0,c[1]-90])([0,90-d]));h[1]=d3.geoRotation([c[0],0])(d3.geoRotation([0,c[1]-90])([-120,90-d]));h[2]=d3.geoRotation([c[0],0])(d3.geoRotation([0,c[1]-90])([-240,90-d]));h[3]=h[0];polygons[0]={type:"Polygon",coordinates:[h],data:b[0]}}else for(var l=180/e,k=0;k<e;k++){h=[];var q=l*k*2;h[0]=d3.geoRotation([c[0],0])(d3.geoRotation([0,c[1]-90])([-q,90-d]));h[1]=d3.geoRotation([c[0],0])(d3.geoRotation([0,c[1]-90])([-q-l,90-d]));h[2]=
d3.geoRotation([c[0],0])(d3.geoRotation([0,c[1]-90])([-q-2*l,90-d]));h[3]=c;h[4]=h[0];polygons[k]={type:"Polygon",coordinates:[h],data:b[k]}}c=polygons;return c},function(a){return a.data});var c=function(a){var b=a[9];"Travel Team"==a[11]&&(b+=" A");return b+" Rank: "+a[7]+" in Group "+a[1]};cgcs.exit().remove();cgcs.enter().append("path").merge(cgcs).style("fill",function(a){return scolmap.get(a.data)}).style("fill-opacity",.5).style("stroke","black").style("stroke-width","0.5px").attr("clip-path",
"url(#clip)").attr("d",path).on("mouseover",function(a,d){var e=b.get(this).get(a.data),f=d3.nest().key(function(a){return"Travel Team"==a[11]?a[9]:a[10]}).map(e),e=[].concat($jscomp.arrayFromIterable(f.keys())),h={},l=h[e[0]]=0;for(d=1;d<e.length;d+=1)l+=f.get(e[d-1]).length+2,h[e[d]]=l;var k=[15,15];txt=svg.select("#tooltip-map-text").style("display","inline").attr("x",k[0]+25).attr("y",k[1]+35).selectAll("text").data([].concat($jscomp.arrayFromIterable(f.keys())),function(a){return a});txt.exit().remove();
txtenter=txt.enter().append("text").attr("class","leaguename").attr("x",k[0]+25).attr("y",function(a){return k[0]+35+h[a]*em}).merge(txt).text(function(a){return a});txtenter.selectAll("tspan").data(function(a){return f.get(a)},function(a){return a[9]}).enter().append("tspan").attr("x",k[0]+35).attr("dy","1.2em").text(c);bbox=svg.select("#tooltip-map-text").node().getBBox();svg.select("#tooltip-map").style("display","inline").attr("width",bbox.width+20).attr("height",bbox.height+20).attr("x",k[0]+
15).attr("y",k[1]+15)}).on("mouseout",function(a,b){svg.select("#tooltip-map").style("display","none");svg.select("#tooltip-map-text").style("display","none")})}
function init_list(){gmenu=d3.select("#group select");-1==menu_vars.group&&(gmenu.property("value",0),menu_vars.group=0,change_filter());ALLoption=gmenu.select("option");ALLoption.attr("disabled",!0);header.style("visibility","visible");group=svg.insert("g").attr("class","listlayer").attr("transform","translate(0,"+Math.round(2.3*em)+")");div.style("overflow-y","auto");d3.select("#markertoggle").style("visibility","hidden");d3.select("#locatortoggle").style("visibility","hidden")}
function destroy_list(){group.remove();header.style("visibility","hidden");header2.style("visibility","hidden")}var listcomp=null;function selectcompare(a,b,d){listcomp=null===listcomp?a:listcomp[0]==a[0]?null:a;redraw_list()}var hta=.041;function wftda_scores(a){return 0<median*listcomp[3]-a[3]?(a[3]*a[3]/(listcomp[3]*listcomp[3])).toPrecision(3):(a[3]*a[3]/(listcomp[3]*listcomp[3])).toPrecision(3)+" RANK TOO HIGH"}
function srd_scores(a){var b=Math.exp(a[3]-listcomp[3]);a=Math.exp(parseFloat(a[4])+parseFloat(listcomp[4]))-1;return b.toPrecision(3)+"\u00b1"+(Math.abs(b*a)/2).toPrecision(2)}function wftda_colours(a){return a[0]==listcomp[0]?"#505":+a[3]>+listcomp[3]?"#A00":"#00A"}function srd_colours(a){var b=+a[3]-listcomp[3];a=parseFloat(a[4])+parseFloat(listcomp[4]);if(Math.abs(b)>a)return 0<b?"#A00":"#00A";b/=a;return"rgb("+65*(1+Math.round(b))+",0,"+65*(1-Math.round(b))+")"}
function redraw_list(){function a(a){return"Travel Team"==a[11]?a[9]+" A":"Exhibition Team"==a[11]?a[9]:a[9]+" of "+a[10]}function b(b){source=.7*em*a(b).length;return-2<source-e?e:source}var d=menu_vars.col;bb=div.node().getBoundingClientRect();var c=bb.right-bb.left,e=c-62-22*em;console.log(e);if("SRDRank"==r_key||"SRDRank2.2"==r_key){var m=srd_scores;var n=srd_colours}else m=wftda_scores,n=wftda_colours;null===listcomp?(group.attr("transform","translate(0,"+Math.round(2.3*em)+")"),header2.style("visibility",
"hidden")):(group.attr("transform","translate(0,"+Math.round(5.6*em)+")"),header2.style("visibility","visible"),header2.attr("width",c),header2.style("top",bb.top+2.3*em),header2.select(".teamname").attr("x",c/2-22).text(a(listcomp)).attr("textLength",b(listcomp)),header2.select(".wl").attr("x",c/2-22),header2.select(".endnote").attr("x",c-50),header2.select("rect").attr("width",c-20));svg.attr("height",Math.round(3.3*(sortedr.length+2)*em));svg.attr("width",c);var f=group.selectAll("g").data(sortedr,
function(a){return a[0]});f.exit().transition("x").duration(500).remove();f.exit().select("rect").transition("x").duration(499).attr("fill-opacity",0);f.exit().select("text").transition("x").duration(499).attr("fill-opacity",0);genter=f.enter().insert("g").attr("transform",function(a,b){return"translate(5,"+(Math.round(3.3*b*em)+5)+")"}).on("click",selectcompare);grects=genter.append("rect").attr("fill",function(a){return scolmap.get(colmap[d](a))}).attr("class","barcontent").attr("fill-opacity",
0).attr("stroke-opacity",0).attr("stroke",function(a){return null!==listcomp?n(a):"#444"}).attr("stroke-width",function(a){return null!==listcomp?3:1}).attr("width",c-10).attr("height","3em");genter.append("text").attr("class","rank").attr("x",5).attr("y","2em").text(function(a){return a[8]});genter.append("text").attr("class","purerank").attr("x",5+5*em).attr("y","2em").text(function(a){return"("+a[7]+")"});genter.append("text").attr("class","teamname").attr("x",c/2-22).attr("y","2em").attr("text-anchor",
"middle").attr("textLength",b).text(a);null===listcomp?genter.append("text").attr("class","rating").attr("x",c-110).attr("y","2em").attr("text-anchor","end").text(function(a){return a[3]+"\u00b1"+a[4]}):genter.append("text").attr("class","rating").attr("x",c-110).attr("y","2em").attr("text-anchor","end").text(m);genter.append("a").attr("xlink:href",function(a){return"http://flattrackstats.com/teams/"+a[0]}).attr("target","_blank").append("image").attr("xlink:href","fts-logo-sm.png").attr("y","1em").attr("x",
c-65);header.attr("width",c);header.style("top",bb.top);header.select("rect").attr("width",c-20);header.select(".rank").attr("x",5);header.select(".purerank").attr("x",5+5*em);header.select(".teamname").attr("x",c/2-22);header.select(".rating").attr("x",c-110);header.select(".rating").text("Rating");grects.transition("x").delay(500).duration(500).attr("fill-opacity",.3).attr("stroke-opacity",1);genter.selectAll("text").transition("x").delay(500).duration(500).attr("fill-opacity",1);f.select("rect").attr("stroke",
function(a){return null!==listcomp?n(a):"#444"}).attr("stroke-width",function(a){return null!==listcomp?3:1});f.select(".rank").text(function(a){return a[8]});f.select(".purerank").text(function(a){return"("+a[7]+")"});f.select("rect").attr("width",c-20);f.select(".teamname").attr("x",c/2-22).attr("textLength",b);null===listcomp?f.select(".rating").attr("x",c-110).text(function(a){return a[3]+"\u00b1"+a[4]}):f.select(".rating").text(m);f.select("image").attr("x",c-65);f.transition("x").duration(500).attr("transform",
function(a,b){return"translate(5,"+(Math.round(3.3*b*em)+5)+")"});f.select("rect").transition("x").duration(500).attr("fill",function(a){return scolmap.get(colmap[d](a))})};
